users:
  ananos:
    name: Anastassios Nanos
    email: ananos@nubificus.co.uk
  cmainas:
    name: Charalampos Mainas
    email: cmainas@nubificus.co.uk
  gntouts:
    name: Georgios Ntoutsos
    email: gntouts@nubificus.co.uk
  johnp41:
    name: Ioannis Plakas
    email: iplakas@nubificus.co.uk
  mgkeka-nbfc:
    name: Maria Gkeka
    email: mgkeka@nubificus.co.uk
  panosmaurikos:
    name: Panagiotis Mavrikos
    email: pmavrikos@nubificus.co.uk
  zyfy29:
    name: zyfy29
    email: wasuremono127@gmail.com
  copilot-pull-request-reviewerbot:
    name: copilot[bot]
    email: copilot[bot]@users.noreply.github.com
  dependabotbot:
    name: dependabot[bot]
    email: support@github.com
