name: urunc CI
on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
      skip-build:
        required: false
        type: string
        default: "no"
      skip-lint:
        required: false
        type: string
        default: "no"
      go_version:
        required: false
        type: string
        default: "1.24.1"

permissions:
  contents: read
  pull-requests: read
  packages: write
  id-token: write
  attestations: write

jobs:
  validate-files-and-commits:
    if: ${{ inputs.skip-lint != 'yes' }}
    name: Lint Files & commits 
    uses: ./.github/workflows/validate-files-and-commits.yml
    with:
      ref: ${{ inputs.ref }}
    secrets: inherit

  lint:
    name: Lint code
    if: ${{ inputs.skip-lint != 'yes' }}
    uses: ./.github/workflows/lint.yml
    with:
      ref: ${{ inputs.ref }}
      go_version: ${{ inputs.go_version }}
    secrets: inherit

  build:
    if: ${{ inputs.skip-build != 'yes' }}
    name: Build
    uses: ./.github/workflows/build.yml
    with:
      ref: ${{ inputs.ref }}
      go_version: ${{ inputs.go_version }}
    secrets: inherit

  unit_test:
    if: ${{ inputs.skip-build != 'yes' }}
    name: Unit tests
    uses: ./.github/workflows/unit_test.yml
    with:
      ref: ${{ inputs.ref }}
      go_version: ${{ inputs.go_version }}
    secrets: inherit

  vm_test:
    if: ${{ inputs.skip-build != 'yes' }}
    needs: [build,unit_test]
    name: E2E test
    uses: ./.github/workflows/vm_test.yml
    with:
      ref: ${{ inputs.ref }}
      go_version: ${{ inputs.go_version }}
      runner-archs: '["amd64", "arm64"]'
      runc_version: '1.3.0'
      containerd_version: '2.1.3'
      cni_version: '1.7.1'
      nerdctl_version: '2.1.3'
      crictl_version: 'v1.30.0'
      firecracker_version: 'v1.7.0'
      solo5_version: 'v0.9.0'
    secrets: inherit

  kind_test:
    if: ${{ inputs.skip-build != 'yes' }}
    needs: [build, unit_test]
    name:  Kubernetes test
    uses: ./.github/workflows/kind_test.yml
    with:
      ref: ${{ inputs.ref }}
      firecracker_version: 'v1.7.0'
      solo5_version: 'v0.9.0'
      runc_version: '1.3.0'
    secrets: inherit
