name: Validate Files and Commit Messages

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
        default: ''

jobs:
  linter-commitlint:
    name: Lint Commit Messages
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - arch: amd64
            runner: ubuntu-22.04
      fail-fast: false
    defaults:
      run:
        working-directory: .github/linters


    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '22'

      - run: npm install --legacy-peer-deps

      - name: Run commitlint
        run: |
          git fetch origin main --depth=1
          npx commitlint --from=origin/main --config ./commitlint.config.js

  linter-typos:
    name: Spell Check Repo
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - arch: amd64
            runner: ubuntu-22.04
      fail-fast: false

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
  
      - name: Setup Node.js (for cspell)
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '20'
  
      - name: Install cspell
        run: npm install -g cspell
  
      - name: Spell check repo
        run: cspell --config .github/linters/.cspell.json
  

  linter-license-eye:
    name: Check License Headers
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - arch: amd64
            runner: ubuntu-22.04
      fail-fast: false

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Fix paths
        run: |
          echo "Unset GO PATH, as the following action conflicts with the already installed version"
          export GOPATH=
          echo "GOPATH=${GOPATH}" >> "$GITHUB_ENV"
          export GOTOOLDIR=
          echo "GOTOOLDIR=${GOTOOLDIR}" >> "$GITHUB_ENV"
          export GOROOT=
          echo "GOROOT=${GOROOT}" >> "$GITHUB_ENV"
        shell: bash

      - name: Run license-eye
        uses: apache/skywalking-eyes/header@07a607ff5b0759f5ed47306c865aac50fe9b3985 # main
        with:
          config: .github/linters/licenserc.yml
          token: ${{ secrets.GITHUB_TOKEN }}
